[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "is-lab"
version = "0.1.0"
description = "Information Security Lab Work"
authors = [
  { name="", email="" }
]
dependencies = [
    "numpy",
]
